### ISSUE TITLE
窄屏下置顶图标消失

### ISSUE THREAD

**Issue by zhang-san-eng** [zchengsite/hexo-theme-oranges#100]
减小浏览器宽度（或使用手机访问），当目录缩回右上角时，置顶图标消失，但是元素还在，还可以点击。如何解决？

**Comment by zchengsite** [comment]
目前通过设置元素透明度实现
```css
opacity: 0;
```
替换为以下方案，即可解决问题
```css
display: none;
```

感谢反馈🍻，已记录待办，最近会优化

**Comment by zhang-san-eng** [comment]
感谢，问题已解决： 
```css
.back-to-top {
    opacity: 1;
    z-index: -1;
  }
```
