### ISSUE TITLE
修改中文不起作用

### ISSUE THREAD

**Issue by tsiayigong** [zchengsite/hexo-theme-oranges#104]
修改根目录下的`_config.yml`文件中的`language`项为`zh-CN`后，使用`hexo s`得到的依然是英文结果，请问这是一个bug么？
```yml
# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: zh-CN
timezone: ''
```
