### ISSUE TITLE
对于一些LaTex显示有问题

### ISSUE THREAD

**Issue by Dimp07** [zchengsite/hexo-theme-oranges#111]
在markdown中显示为
![image](https://github.com/zchengsite/hexo-theme-oranges/assets/129408828/c51fb6f4-e41e-40a3-88e7-19f12f3761b4)
![image](https://github.com/zchengsite/hexo-theme-oranges/assets/129408828/faa88826-59ed-4d16-9130-abbb76dab775)
但是在页面中显示为
![image](https://github.com/zchengsite/hexo-theme-oranges/assets/129408828/afdecad7-0d4b-4b9f-9753-f7339e707f8c)

**Comment by ihanofficial** [comment]
我这边有解决方案
更改一下latex的渲染方式即可
把mathjax的js cdn改成latex的就行

---

在_config.oranges.yml配置如下（将mathjax替换为以下内容：

```yaml
  latex:
    enable: true
    # url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js  原作者给出的的渲染js
    url: https://cdn.jsdelivr.net/npm/latex@0.0.1/texwrapper.min.js
```

你那边测试下是否可用
