### ISSUE TITLE
关于文章中 RSS 的 URL 错误的问题

### ISSUE THREAD

**Issue by xQmQ** [zchengsite/hexo-theme-oranges#45]
## 问题描述

以`www.blog.com`为博客域名举例：

在 **主页** 点击 RSS 图标，会跳转到**正确**的 RSS URL：`www.blog.com/atom.xml`

在 **标签** 点击 RSS 图标，会跳转到**错误**的 RSS URL：`www.blog.com/tags/atom.xml`

在 **任意一篇文章** 点击 RSS 图标，会跳转到**错误**的 RSS URL：`www.blog.com/posts/atom.xml`

## 相关配置

插件：hexo-generator-feed

`blog/_config.yml`：

```yml
url: http://www.blog.com/
root: /
permalink: posts/:abbrlink.html

theme: oranges

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
```

`blog/themes/oranges/_config.yml`：

```yml
# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
    key: home
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags
    
# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # RSS
    -
      name: rss
      icon: rss
      path: atom.xml
```

## 问题原因猜测

不了解前端知识，个人猜测是页脚的`path`设置问题，导致直接拼接到 URL 上

## 个人当前解决方案

更改`blog/themes/oranges/_config.yml`中 RSS 的`paht`，更改后发现问题得到解决

```yml
# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # RSS
    -
      name: rss
      icon: rss
      path: http://www.blog.com/atom.xml
```

但是这种方案，不是很美观，在更换域名或某些操作时，需要处理

**Comment by zchengsite** [comment]
我这边验证了下，没有出现你说的这个问题。
尝试在path中加入`/`看能否解决问题，如下：
```
feed:
  type: atom
  path: /atom.xml
```

**Comment by xQmQ** [comment]
对比了 hexo 配置文件和 theme 配置文件，发现是 theme 配置文件中的问题，正确配置应该如下

```yml
footer:
  social:
    -
      name: rss
      icon: rss
      path: /atom.xml
```

查看仓库中 theme 的配置文件中正常的，但是 README 中给出了错误的配置 `path: atom.xml`
