### ISSUE TITLE
关于页脚不能紧靠页面底部

### ISSUE THREAD

**Issue by Noicdi** [zchengsite/hexo-theme-oranges#68]
出于进一步简洁页面的目的，我对 avatar 的相关代码设置了 `enable`，去掉了头像和昵称。

```
# 用户头像与昵称
avatar:
  enable: false
  author_photo: /images/avatar.ico
  author_nickname: 三尺微命，一介书生
  path: /
```

主页和文章等页面，内容足够多，使页脚可以紧靠页面底部，但是其他一些页面内容不够多，页脚不能紧靠页面底部，[实例](https://www.xqmq.icu/tags/)

请教一个解决方案，谢谢
