### ISSUE TITLE
我无法使用waline评论

### ISSUE THREAD

**Issue by JerryYang-git** [zchengsite/hexo-theme-oranges#75]
在更新主题之后，查看到有waline的相关配置，我将下方waline的JS URL更新为`https://unpkg.com/@waline/client@v2/dist/waline.js`
把相关的开关打开并配置好waline评论链接后，文章评论直接关闭了，由于我储备的开发知识很少，实在不知道问题出在哪里了，请求帮助，万分感谢

**Comment by zchengsite** [comment]
能否贴出相关配置文件代码，我这边看下

**Comment by JerryYang-git** [comment]
我的`_config.oranges.yml`文件中评论相关的配置，为确保主题为最新，我直接重新git拉了主题文件下来了。

```
# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId: 
    appKey: 
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io
  
  # waline https://waline.js.org
  waline:
    enable: true
    serverURL: waline-deployment.vercel.app
```

```
  # 评论系统
  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: true
      url: https://unpkg.com/@waline/client@v2/dist/waline.js
```
