### ISSUE TITLE
gittalk 无法使用

### ISSUE THREAD

**Issue by marchocode** [zchengsite/hexo-theme-oranges#82]
gitalk 配置后无法使用 控制台也没有报错，但是valine 正常

```
  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: true
    clientID: c2b****8a********
    clientSecret: *********************e9ba2775225f
    repo: "marchocode.github.io"
    owner: marchocode
    admin: marchocode
    id: location.pathname
    distractionFreeMode: false
```
