### ISSUE TITLE
代碼高亮

### ISSUE THREAD

**Issue by tsengtinghan** [zchengsite/hexo-theme-oranges#85]
請問如果想開啟代碼高亮是要修改theme裡面的config嗎? 還是根目錄裡的config?
```
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:
```
我新增了這段後C++的關鍵字都還是無法有高亮的效果，麻煩你們解答了謝謝!
