### ISSUE TITLE
waline的一点问题

### ISSUE THREAD

**Issue by zlx021120** [zchengsite/hexo-theme-oranges#91]
作者你好，再一次麻烦您
我在使用waline过程中遇到了三个问题
一个是waline评论区显示效果有点问题
一个是控制台似乎提示我使用什么v2 CDN
还有就是我关闭cdn那个就不会显示waline，但是jsdelivr似乎有些慢
我的相关评论 [链接](https://blog.tanglu.me/webmail/) 我的主题配置文件如下
```
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId: FP5iDHnhAB22BwHHA109y2Sg-MdYXbMMI
    appKey: T2bVelavTppevO939KvvxbYO
    placeholder: Welcome
    avatar: retro
    vempty_display: false
    serverURLs: https://fp5idhnh.api.lncldglobal.com

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io
  
  # waline https://waline.js.org
  waline:
    enable: true
    serverURL: https://waline.tanglu.me
```

```
cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # LaTeX 公式
  mathjax:
    enable: false
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  # 代码块复制
  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  # 评论系统
  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: true
      url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js
```

![image](https://user-images.githubusercontent.com/92848326/228836424-0ee5bca5-fd89-415c-9108-4df32172ec89.png)

**Comment by hiBlunt** [comment]
1.首先请确保使用了最新版本的oranges代码。
2.url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js这个是waline v1版本的js文件。因为waline已经升级到v2版本，所以oranges也随之升级。这里的配置你可以修改为
```
waline:
      enable: true
      url: 
        css: https://unpkg.com/@waline/client@v2/dist/waline.css
        js: https://unpkg.com/@waline/client@v2/dist/waline.mjs

```
3. jsdeliver速度十分缓慢，建议使用其他cdn
