### ISSUE TITLE
新手求助，本地化部署失败

### ISSUE THREAD

**Issue by RealZhuoZhuo** [zchengsite/hexo-theme-oranges#98]
本来已经在github pages上成功部署了，过了半个月准备发篇文章却本地化部署都失败了![屏幕截图 2023-08-27 113630.png](https://github.com/zchengsite/hexo-theme-oranges/assets/111571462/f7f300e5-c59c-474f-8e9c-6c74313df17e)

![屏幕截图 2023-08-27 113639.png](https://github.com/zchengsite/hexo-theme-oranges/assets/111571462/3fc07680-7b4e-407b-999b-ab30d2e7de45)

请问该如何解决

**Comment by zchengsite** [comment]
看报错信息是主题配置文件_config.yml中页脚信息footer下的social内容有问题，检查下social下的项目，确保至少保留一项。参考
```yaml
social:
    -
      name: github
      icon: github
      path: https://github.com/zchengsite/hexo-theme-oranges
```
具体可见：[_config.yml](https://github.com/zchengsite/hexo-theme-oranges/blob/master/_config.yml#L136)

> 本来已经在github pages上成功部署了，过了半个月准备发篇文章却本地化部署都失败了![屏幕截图 2023-08-27 113630.png](https://user-images.githubusercontent.com/111571462/263509501-f7f300e5-c59c-474f-8e9c-6c74313df17e.png)
> 
> ![屏幕截图 2023-08-27 113639.png](https://user-images.githubusercontent.com/111571462/263509504-3fc07680-7b4e-407b-999b-ab30d2e7de45.png)
> 
> 请问该如何解决
